### ISSUE TITLE
Improve function to find targets

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman#1]
The module **process.py** contains a class Process.

The method _identify_spectra_ is not written in an elegant way thus is a bit hard to read.

**Comment by simontorres** [comment]
started a set of simulation tools in order to identify the most conflictive steps/conditions and hopefully improve the extraction

**Comment by simontorres** [comment]
Detection works nicely, extraction needs focus.

**Comment by simontorres** [comment]
I might use what @b1quint described in #4 
```python
import astropy.io.fits as pyfits
import numpy as np
from scipy import signal
spec = pyfits.getdata(filename)
foo = np.where(np.abs(spec > spec.min() + 0.75 * spec.max()), spec, 0)
maxima = signal.argrelmax(foo, axis=0, order=10)[0]
```
If I can make it work for a single peak.

**Comment by b1quint** [comment]
The 'signal.argrelmax' does not work well on 2D data. It is easier (?) to split each column in a 1D array and work one by one. If needed, you can use 'map' or 'multiprocessing.Pool.map_async'. Here is an example:
'
x = (some 2D array)
order = int(0.25 * x.shape[0])
find_peak = lambda i: signal.argrelmax(x[i], axis=0, order=order)[0]
peaks = map(find_peak, numpy.arange(x.shape[1]))
'

**Comment by simontorres** [comment]
It has been done.
