### ISSUE TITLE
Add Pipeline Version to header in reduced data

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman#108]
An important point arouse from the meeting with Las Cumbres Observatory. To add the pipeline's version to the header of the processed image. The keyword can not be HISTORY instead a new keyword name has to be invented. In fact it might be necessary to define a set of pipeline-specific keywords.

**Comment by cbaorion** [comment]
I think we should use the keyword "VERSION" which will be of type STRING. For example: 1.0b
