### ISSUE TITLE
Build is failing because can't connect to continuum.

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman#124]
@b1quint Could you fix the line in `.travis.yml` that is causing build to fail on travis?

```python
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
```

https://travis-ci.org/soar-telescope/goodman/jobs/305423785

**Comment by simontorres** [comment]
Just checked the links and they both work. So it must be something else.

**Comment by b1quint** [comment]
Did you manage to solve this problem?

**Comment by simontorres** [comment]
Haven't touched it since.

**Comment by simontorres** [comment]
This problem solved itself. Apparently was an internal failure of travis. There are other issues right now but not related to this so I'm closing this issue.
