### ISSUE TITLE
Updated Goodman DRP Webpages

### ISSUE THREAD

**Issue by cbaorion** [soar-telescope/goodman#138]
This is not an issue per se, but I didn't know where else to put it.
Jay pointed out that we didn't mention anywhere in the webpages who the Goodman DRP team are!  He aded us in the main page, but I went in and added us in the About page, in the Contact page in addition to the main page. Now people will actually know who developed the DRP!

Don't know how we missed that!
Ok. So its done, so I will close the issue right away.

**Comment by simontorres** [comment]
I just fixed a typo
