### ISSUE TITLE
Second Release ToDos

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman#17]
- [ ] Enable Extended object spectrum extraction.

__
please add any request/ideas/needs

**Comment by b1quint** [comment]
- [ ] Add/reject points for wavelength solution fit

**Comment by simontorres** [comment]
Zoom/Pick Issue is solved.

**Comment by simontorres** [comment]
- [ ] Create a GUI or create a special class for the matplotlib graphic interface that makes the interactive mode work.

**Comment by simontorres** [comment]
- [ ] Use slit value to estimate argrelmax order (line detection)

**Comment by simontorres** [comment]
This issue is oudated and the only point left is covered in #41 #146
