### ISSUE TITLE
More information about how to use lamps during redspec

### ISSUE THREAD

**Issue by b1quint** [soar-telescope/goodman#70]
The `redspec` script allows the user to give an ASCII file that correlates lamp files and science files but I did not find any documentation explaining what is the expected format. This should be added to the wiki page [How to use the Pipeline](https://github.com/soar-telescope/goodman/wiki/How-to-use-the-Pipeline).

**Comment by simontorres** [comment]
In fact this is not fully implemented and it will raise a `NonImplementedError`. I was thinking to remove this for now and fully implement it for the _final_ release (or future versions)

**Comment by simontorres** [comment]
This feature has been deleted.
