### ISSUE TITLE
End of night calibrations

### ISSUE THREAD

**Issue by b1quint** [soar-telescope/goodman#72]
Calibration data obtained at the end of the night causes science files to be ignored.

**Comment by b1quint** [comment]
One possible solution is to implement a criterium of "belong to the night?" This will be true if the file was obtained within the range of +/- 12h counting from the midnight (example reference 2017-05-29 23:59 CLT).

**Comment by simontorres** [comment]
We decided to process everything that is inside the folder. The only calibration that needs to time-checked are flats and comparison lamps. The criteria would be position in the sky (`OBSRA` and `OBSDEC`). If no calibration is found near to the targets get the any in the folder, provided it is valid.

**Comment by simontorres** [comment]
This issue has been solved but there is a side effect described in Issue #101
