### ISSUE TITLE
Repair cosmic Ray Rejection implementation

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman#85]
Add ability to use the cosmic ray rejection mask created in the first (ccd) pipeline
* when trimming the image `ccd.data`, the `ccd.mask` attribute must be trimmed as well.

If there hasn't been a cosmic ray rejection the `mask` attribute is a `None`

**Comment by simontorres** [comment]
The cosmic ray rejection mechanism is not working properly. We are using astropy' LACosmic, David explained to me that LACosmic was not designed for spectroscopy and suggested to use [this code](http://users.camk.edu.pl/pych/DCR/). I installed it and tried and seems to work much better. See the animation in full screen and zoom it if necessary.

![cray_animation](https://user-images.githubusercontent.com/3878895/27358581-5cba700e-55e5-11e7-9cb6-be157f10c012.gif)

**Comment by simontorres** [comment]
I have finally implemented the `dcr` code in the redccd. There are some small issues to be solved like the `dcr.par` file required by `dcr` this is hard coded and can't be changed. The user will have to place a modified version in the raw_data directory or the program will copy a default one.

**Comment by simontorres** [comment]
It works well. In general this will require the user to compile a code. For what I've read it is possible to compile C code when running `python setup.py install` by configuring `setup.py` accordingly but I think this should be left for version 1.0.

**Comment by cbaorion** [comment]
This is ok for the beta version.

**Comment by simontorres** [comment]
This has been fully implemented. There is a possible problem though for data with binning different than 1x1 in such case it is necessary to change the parameters for dcr at `dcr.par`

## Default dcr.par

```shell
THRESH	= 3.0	// Threshold (in STDDEV)
XRAD	= 9	// x-radius of the box (size = 2 * radius)
YRAD	= 9	// y-radius of the box (size = 2 * radius)
NPASS	= 5	// Maximum number of cleaning passes
DIAXIS	= 0	// Dispersion axis: 0 - no dispersion, 1 - X, 2 - Y
LRAD	= 1	// Lower radius of region for replacement statistics
URAD	= 3	// Upper radius of region for replacement statistics
GRAD	= 1	// Growing radius
VERBOSE	= 1	// Verbose level [0,1,2]
END
```

## Modified dcr.par for data with binning 2x2

```shell
THRESH  = 2.0   // Threshold (in STDDEV)
XRAD    = 9     // x-radius of the box (size = 2 * radius)
YRAD    = 9     // y-radius of the box (size = 2 * radius)
NPASS   = 5     // Maximum number of cleaning passes
DIAXIS  = 0     // Dispersion axis: 0 - no dispersion, 1 - X, 2 - Y
LRAD    = 1     // Lower radius of region for replacement statistics
URAD    = 3     // Upper radius of region for replacement statistics
GRAD    = 0     // Growing radius
VERBOSE = 1     // Verbose level [0,1,2]
END
```

You can find the description of those parameter in the paper. http://adsabs.harvard.edu/abs/2004PASP..116..148P

**Comment by simontorres** [comment]
The discussion of parameters variation is discussed here #105
